healthData = [
{"abbreviation": "us-AL", "Location": "Alabama","Male":277.5,"Female":182.5},
{"abbreviation": "us-AK", "Location": "Alaska","Male":188.3,"Female":109},
{"abbreviation": "us-AZ", "Location": "Arizona","Male":171.1,"Female":106.2},
{"abbreviation": "us-AR", "Location": "Arkansas","Male":274,"Female":169.8},
{"abbreviation": "us-CA", "Location": "California","Male":180.5,"Female":111},
{"abbreviation": "us-CO", "Location": "Colorado","Male":164.3,"Female":102.5},
{"abbreviation": "us-CT", "Location": "Connecticut","Male":186.5,"Female":115.3},
{"abbreviation": "us-DC", "Location": "Delaware","Male":211.6,"Female":135.7},
{"abbreviation": "us-DE", "Location": "District of Columbia","Male":262.8,"Female":166.8},
{"abbreviation": "us-FL", "Location": "Florida","Male":192.7,"Female":116.9},
{"abbreviation": "us-GA", "Location": "Georgia","Male":226.4,"Female":143.7},
{"abbreviation": "us-HI", "Location": "Hawaii","Male":184.1,"Female":96.4},
{"abbreviation": "us-ID", "Location": "Idaho","Male":189.6,"Female":121.4},
{"abbreviation": "us-IL", "Location": "Illinois","Male":216.4,"Female":133.5},
{"abbreviation": "us-IN", "Location": "Indiana","Male":232.3,"Female":144.7},
{"abbreviation": "us-IA", "Location": "Iowa","Male":201.1,"Female":123},
{"abbreviation": "us-KS", "Location": "Kansas","Male":202,"Female":121.2},
{"abbreviation": "us-KY", "Location": "Kentucky","Male":255.5,"Female":156.7},
{"abbreviation": "us-LA", "Location": "Louisiana","Male":273.3,"Female":171.6},
{"abbreviation": "us-ME", "Location": "Maine","Male":184.2,"Female":118.1},
{"abbreviation": "us-MD", "Location": "Maryland","Male":216.2,"Female":131.4},
{"abbreviation": "us-MA", "Location": "Massachusetts","Male":178.2,"Female":106.3},
{"abbreviation": "us-MI", "Location": "Michigan","Male":250.8,"Female":161},
{"abbreviation": "us-MN", "Location": "Minnesota","Male":152.3,"Female":88.3},
{"abbreviation": "us-MS", "Location": "Mississippi","Male":287.7,"Female":184.5},
{"abbreviation": "us-MO", "Location": "Missouri","Male":244.6,"Female":154.5},
{"abbreviation": "us-MT", "Location": "Montana","Male":181.5,"Female":116.2},
{"abbreviation": "us-NE", "Location": "Nebraska","Male":186.3,"Female":108.5},
{"abbreviation": "us-NV", "Location": "Nevada","Male":251.7,"Female":148.1},
{"abbreviation": "us-NH", "Location": "New Hampshire","Male":183.1,"Female":119.5},
{"abbreviation": "us-NJ", "Location": "New Jersey","Male":208.5,"Female":134.1},
{"abbreviation": "us-NM", "Location": "New Mexico","Male":182.4,"Female":109.9},
{"abbreviation": "us-NY", "Location": "New York","Male":221.6,"Female":145.2},
{"abbreviation": "us-NC", "Location": "North Carolina","Male":205.2,"Female":123.3},
{"abbreviation": "us-ND", "Location": "North Dakota","Male":185,"Female":115.7},
{"abbreviation": "us-OH", "Location": "Ohio","Male":237.1,"Female":146.9},
{"abbreviation": "us-OK", "Location": "Oklahoma","Male":280.3,"Female":184.4},
{"abbreviation": "us-OR", "Location": "Oregon","Male":169.5,"Female":102.1},
{"abbreviation": "us-PA", "Location": "Pennsylvania","Male":223.5,"Female":139.1},
{"abbreviation": "us-RI", "Location": "Rhode Island","Male":214.9,"Female":122.1},
{"abbreviation": "us-SC", "Location": "South Carolina","Male":231.5,"Female":140.5},
{"abbreviation": "us-SD", "Location": "South Dakota","Male":208.4,"Female":111.9},
{"abbreviation": "us-TN", "Location": "Tennessee","Male":255.5,"Female":164.7},
{"abbreviation": "us-TX", "Location": "Texas","Male":213.9,"Female":134.4},
{"abbreviation": "us-UT", "Location": "Utah","Male":176.8,"Female":128.7},
{"abbreviation": "us-VT", "Location": "Vermont","Male":190.1,"Female":129.5},
{"abbreviation": "us-VA", "Location": "Virginia","Male":196.8,"Female":124.3},
{"abbreviation": "us-WA", "Location": "Washington","Male":179.4,"Female":103.2},
{"abbreviation": "us-WV", "Location": "West Virginia","Male":243.6,"Female":152.3},
{"abbreviation": "us-WI", "Location": "Wisconsin","Male":196.6,"Female":121.5},
{"abbreviation": "us-WY", "Location": "Wyoming","Male":199.9,"Female":126.9}]
